{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.host.name }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  name: {{ .Values.service.serverPort.name }}
            {{- if .Values.useNamespaceForIngress | default false }}
            path: /{{ .Release.Namespace }}/{{ .Values.ingress.path }}
            {{- else }}
            path: /{{ .Values.ingress.path }}
            {{- end}}
            pathType: {{ .Values.ingress.pathType }}
          {{- if .Values.mcp.enabled }}
          # MCP server routes
          - backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  name: {{ .Values.service.mcpPort.name }}
            path: /mcp
            pathType: Prefix
          # MCP WebSocket endpoint
          - backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  name: {{ .Values.service.mcpPort.name }}
            path: /mcp/ws
            pathType: Prefix
          {{- end }}
{{- end}}
