apiVersion: v1
kind: Secret
metadata:
  name: ai-secrets
  annotations:
    "helm.sh/hook": "pre-install, pre-upgrade, pre-delete"
    "helm.sh/hook-weight": "-50"
type: Opaque
data:
  {{- range $key, $value := .Values.container.env.secretVars }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}