# Constants
from enum import Enum

CAN_PROCEED = "can_proceed"
PROMPT = "prompt"
ANSWER = "answer"
FUNCTION = "function"
QUESTION = "question"
NOTIFICATION = "notification"
INFO = "info"
PROCESSORS_STACK = "PROCESSORS"
ENTITY_STACK = "ENTITY"
WORKFLOW_STACK = "WORKFLOW"
EXTERNAL_SOURCES_PULL_BASED_RAW_DATA = "EXTERNAL_SOURCES_PULL_BASED_RAW_DATA"
WEB_SCRAPING_PULL_BASED_RAW_DATA = "WEB_SCRAPING_PULL_BASED_RAW_DATA"
TRANSACTIONAL_PULL_BASED_RAW_DATA = "TRANSACTIONAL_PULL_BASED_RAW_DATA"
API_REQUEST_STACK = "API_REQUEST"
SCHEDULED_STACK = "SCHEDULED"
EMPTY_PROMPT = "Thank you!"

API_V_CONNECTIONS_ = "api/v1/connections"
API_V_CYODA_ = "api/v1/cyoda"
API_V_WORKFLOWS_ = "api/v1/workflows"
API_V_RANDOM_ = "api/v1/random"
DEEPSEEK_CHAT = "deepseek-chat"
REQUIREMENT_AGENT = "requirement_agent"
EDITING_AGENT = "editing_agent"
APP_BUILDER_MODE = "app_builder"
DEPLOY_CYODA_ENV = "cyoda_env"
DEPLOY_USER_APP = "user_app"
DEPLOY_STATUS = "deploy_status"
FSM_CYODA = "cyoda"
FSM_LOCAL = "local"
EDGE_MESSAGE_CLASS = "net.cyoda.saas.message.model.EdgeMessage"
TREE_NODE_ENTITY_CLASS = "com.cyoda.tdb.model.treenode.TreeNodeEntity"
UPDATE_TRANSITION = "update_transition"
QUESTIONS_QUEUE_MODEL_NAME = "questions_queue"
MEMORY_MODEL_NAME = "chat_memory"
FLOW_EDGE_MESSAGE_MODEL_NAME = "flow_edge_message"
AI_MEMORY_EDGE_MESSAGE_MODEL_NAME = "ai_memory_edge_message"
EDGE_MESSAGE_STORE_MODEL_NAME = "edge_message_store"
CHAT_MODEL_NAME = "chat_entity"
AGENTIC_FLOW_ENTITY = "agentic_flow_entity"
GEN_APP_ENTITY_PYTHON = "build_general_application_python"
GEN_APP_ENTITY_JAVA = "build_general_application_java"
GENERATING_GEN_APP_WORKFLOW = "generating_gen_app_workflow"
SCHEDULER_ENTITY = "scheduler_entity"
ADD_NEW_FEATURE = "edit_existing_app_design_additional_feature"
ADD_NEW_ENTITY = "add_new_entity_for_existing_app"
ADD_NEW_WORKFLOW = "add_new_workflow"
EDIT_API_EXISTING_APP = "edit_api_existing_app"
EDIT_EXISTING_WORKFLOW = "edit_existing_workflow"
EDIT_EXISTING_PROCESSORS = "edit_existing_processors"
TRANSFER_CHATS_ENTITY = "transfer_chats_entity"

GIT_BRANCH_PARAM = "git_branch"
LOCKED_CHAT = "locked_chat"
FINISH_WORKFLOW = "finish_workflow"

PUSH_NOTIFICATION = "push_notification"
APPROVE = "let's proceed to the next iteration immediately: set require additional questions to False and finish the discussion."
RATE_LIMIT = 300
SCHEDULER_CHECK_INTERVAL=60

class GetCyodaGuidelinesData(str, Enum):
    GENERATE_WORKFLOW = "generate_workflow"
    GENERATE_PROCESSORS = "generate_processors"
    CONFIGURE_TRINO = "configure_trino"
    GENERATE_ENTITY = "generate_entity"
    START_APP = "start_app"
    CYODA_BEST_PRACTICE = "cyoda_best_practice"
